#!/usr/bin/env php
<?php

define('DS', DIRECTORY_SEPARATOR);
define('APPLICATION_PATH', realpath(dirname(__FILE__) . '/application'));

set_include_path(dirname(__FILE__) . '/library' . PATH_SEPARATOR . get_include_path());


use Lunch\Cmd;

chdir(dirname(__FILE__));
require_once ('Zend/Loader/Autoloader.php');
require_once ('Lunch/Cmd.php');

$autoloader = Zend_Loader_Autoloader::getInstance();
$autoloader->setFallbackAutoloader(true);

$cmd = Cmd::getInstance();

if (count($argv) > 1) {

    $cmd->run($argv);

} else {
   $cmd->cmdList(); 
}
