
<h2>-- Button --</h2>

<h3>Usage.</h3>

<p>include "button.js" & "button.css"</p>

<pre name="code" class="xml">
<link href="/lunch-pack/css/button.css" rel="stylesheet" type="text/css" />
<script src="/lunch-pack/js/button.js" type="text/javascript" ></script>
</pre>

<p>↓ for example...</p>

<pre name="code" class="xml">
<input class="lunch-button" type="button" value="submit" />
</pre>
<input type="button" class="lunch-button" value="submit" />
<br /><br />


<pre name="code" class="xml">
<input class="lunch-button-caution" type="button" value="caution" />
</pre>
<input class="lunch-button-caution" type="button" value="caution" />
<br /><br />


<pre name="code" class="xml">
<input class="lunch-button-success" type="button" value="success" />
</pre>
<input class="lunch-button-success" type="button" value="success" />
<br /><br />


<pre name="code" class="xml">
<input class="lunch-button-info" type="button" value="info" />
</pre>
<input class="lunch-button-info" type="button" value="info" />
<br /><br />
