
<h2>-- Filed --</h2>

<h3>Usage.</h3>

<p>include "field.js" & "field.css"</p>

<pre name="code" class="xml">
<link href="/lunch-pack/css/field.css" rel="stylesheet" type="text/css" />
<script src="/lunch-pack/js/field.js" type="text/javascript" ></script>
</pre>

<p>↓ for example...</p>

<pre name="code" class="xml">
<input class="lunch-field" type="text" />
</pre>
<input class="lunch-field" type="text" placeholder="lunch-field" />
<br /><br />


<pre name="code" class="xml">
<input class="lunch-field-caution" type="text" />
</pre>
<input class="lunch-field-caution" type="text" placeholder="lunch-field-caution" />
<br /><br />


<pre name="code" class="xml">
<input class="lunch-field-success" type="text" />
</pre>
<input class="lunch-field-success" type="text" placeholder="lunch-field-success" />
<br /><br />
