
<h2>-- Label --</h2>

<h3>Usage.</h3>

<p>include "<span style="font-weight:bold;">labels.css</span>"</p>

<pre name="code" class="xml">
<link href="/lunch-pack/css/labels.css" rel="stylesheet" type="text/css" />
</pre>

<p>↓ for example...</p>

<pre name="code" class="xml">
<p><span class="lunch-label-success">new!</span>hello world!</p>
</pre>

<p><span class="lunch-label-success">new!</span>hello world!</p>
<br />


<pre name="code" class="xml">
<p><span class="lunch-label-caution">caution!</span>don't touch me!</p>
</pre>

<p><span class="lunch-label-caution">caution!</span>don't touch me!</p>
<br />


<pre name="code" class="xml">
<p><span class="lunch-label-warning">warning!</span>danger!</p>
</pre>

<p><span class="lunch-label-warning">warning!</span>danger!</p>
<br />


<pre name="code" class="xml">
<p><span class="lunch-label-note">note</span>updated by 2011/11/15.</p>
</pre>

<p><span class="lunch-label-note">note</span>updated by 2011/11/15.</p>
<br />
