
<h2>Label:</h2>

<p>you can generate label.<br />
this label framework is very usefull.</p>

<p>for examples.</p>

<p>require once lunch-pack css, "<span style="font-weight:bold;">labels.css.</span>"</p>

<pre name="code" class="xml">
<link href="/lunch-pack/css/labels.css" rel="stylesheet" type="text/css" />
</pre>

<p>and...</p>

<pre name="code" class="xml">
<p>hello, world! welcome to here!<span class="lunch-label-success">new!</span></p>
</pre>

<p>hello, world! welcome to here!<span class="lunch-label-success">new!</span></p>
