
<h2>-- Menu --</h2>

<h3>Usage.</h3>

<p>include "menu.js" & "menu.css"</p>

<pre name="code" class="xml">
<link href="/lunch-pack/css/menu.css" rel="stylesheet" type="text/css" />
<script src="/lunch-pack/js/menu.js" type="text/javascript"></script>
</pre>

<p>↓ for example...</p>

<pre name="code" class="xml">
<div class="lunch-menu">
    <input type="button" class="lunch-menu-button" value="Menu" />
    <ul class="lunch-menu-list">
        <li>File</li>
        <li>Copy</li>
        <li>Past</li>
        <li>Exit</li>
    </ul>
</div>
</pre>

<div class="lunch-menu">
    <input type="button" class="lunch-menu-button" value="Menu" />
    <ul class="lunch-menu-list">
        <li>File</li>
        <li>Copy</li>
        <li>Past</li>
        <li>Exit</li>
    </ul>
</div>
<br />
