        <h2>Sorry!</h2>

        <div class="errors">
        
            <p class="error_title">Throw Message: "<?php echo $this->exception->getMessage() ?>"</p>

            <div class="error_file">
                <p><?php echo $this->exception->getFile() . ': line ' . $this->exception->getLine() ?></p>
            </div>

            <p style="padding-top: 20px;">stack trace</p>

            <table border="1" cellpadding="10">
                <?php foreach($this->exception->getTrace() as $t): ?>
                <tr>
                    <td><p>
                        Class: <?php echo $t['class'] ?><br />
                        Method: <?php echo $t['function'] ?><br /><br />
                        <?php echo $t['file'] . ': line ' . $t['line'] ?>
                    </p></td>
                </tr>
                <?php endforeach; ?>
            </table>

        </div>

